### ISSUE TITLE
Keyboard Functionality: Create compact custom keyboard for Android/iOS smartphone view

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/o-crossword#16]
# Keyboard Functionality

## Task: Create compact custom keyboard for Android/iOS smartphone view

As a crossworder
* I want to be able to enter my clues onto a compact keyboard which takes up less of the screen than the default keyboard

So that 
* I can see more of the crossword grid (or clues) when the keyboard is displayed

Requirements
* Android and iOS devices only
- [ ] Keyboard should consist of three rows, centre-aligned, full width, with the following keys:
   * QWERTYUIOP
   * ASDFGHJKL
   * space ZXCVBNM delete
- [x] Pressing space should set (or leave) the current cell blank and moves focus to the next cell of the currently selected word
- [ ] Pressing delete on a filled cell sets the current cell blank
- [ ] Pressing delete on a blank cell acts as backspace + delete to the previous cell in the currently selected word
- [x] Upper case letters only
- [ ] No predictive text bar
- [ ] If the single clue below the grid is selected, the grid and clue scrolls to ensure the single clue is in view above the keyboard
- [ ] If a clue is selected from the list of clues, the page will scroll so that that clue is visible above the keyboard.
- [ ] Keyboard to disappear when
** the display is scrolled (or pinch zoomed)
** A selected clue is unselected
